POST http://localhost:3000/register/
Content-Type: application/json

{
  "user_id":5,
  "username": "adam",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "adam",
  "password": "richard_567"
}

###
GET http://localhost:3000/user/tweets/feed/
Content-Type: application/json



###
GET http://localhost:3000/user/following/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJuYW1lIjoiQWRhbSBSaWNoYXJkIiwidXNlcm5hbWUiOiJhZGFtIiwicGFzc3dvcmQiOiIkMmIkMTAkWllVQnlhOGhDUjFsZjI0Ly5ud0R3LjlFLm82S2Z0TEg3TnloSU1zZE5lSjJxbW5ENnZQbmEiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjc5NTYzNTI1fQ.vE1LAm6XGlUXldIAHA1CB5SuyvByLdOZZCbOvrujMfI



###
GET http://localhost:3000/user/followers/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJuYW1lIjoiQWRhbSBSaWNoYXJkIiwidXNlcm5hbWUiOiJhZGFtIiwicGFzc3dvcmQiOiIkMmIkMTAkWllVQnlhOGhDUjFsZjI0Ly5ud0R3LjlFLm82S2Z0TEg3TnloSU1zZE5lSjJxbW5ENnZQbmEiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjc5NTYzNTI1fQ.vE1LAm6XGlUXldIAHA1CB5SuyvByLdOZZCbOvrujMfI

###
GET  http://localhost:3000/tweets/5/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJuYW1lIjoiQWRhbSBSaWNoYXJkIiwidXNlcm5hbWUiOiJhZGFtIiwicGFzc3dvcmQiOiIkMmIkMTAkWllVQnlhOGhDUjFsZjI0Ly5ud0R3LjlFLm82S2Z0TEg3TnloSU1zZE5lSjJxbW5ENnZQbmEiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjc5NTYzNTI1fQ.vE1LAm6XGlUXldIAHA1CB5SuyvByLdOZZCbOvrujMfI




###
GET http://localhost:3000/tweets/5/likes/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJuYW1lIjoiQWRhbSBSaWNoYXJkIiwidXNlcm5hbWUiOiJhZGFtIiwicGFzc3dvcmQiOiIkMmIkMTAkWllVQnlhOGhDUjFsZjI0Ly5ud0R3LjlFLm82S2Z0TEg3TnloSU1zZE5lSjJxbW5ENnZQbmEiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjc5NTYzNTI1fQ.vE1LAm6XGlUXldIAHA1CB5SuyvByLdOZZCbOvrujMfI




###
GET http://localhost:3000/tweets/5/replies/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJuYW1lIjoiQWRhbSBSaWNoYXJkIiwidXNlcm5hbWUiOiJhZGFtIiwicGFzc3dvcmQiOiIkMmIkMTAkWllVQnlhOGhDUjFsZjI0Ly5ud0R3LjlFLm82S2Z0TEg3TnloSU1zZE5lSjJxbW5ENnZQbmEiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjc5NTYzOTM5fQ.tEW9vqcQ8OmQrFfpN0gZ8U37whhJRpGC84vi63G80Hk



###
GET http://localhost:3000/user/tweets/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJuYW1lIjoiQWRhbSBSaWNoYXJkIiwidXNlcm5hbWUiOiJhZGFtIiwicGFzc3dvcmQiOiIkMmIkMTAkWllVQnlhOGhDUjFsZjI0Ly5ud0R3LjlFLm82S2Z0TEg3TnloSU1zZE5lSjJxbW5ENnZQbmEiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjc5NTYzNTI1fQ.vE1LAm6XGlUXldIAHA1CB5SuyvByLdOZZCbOvrujMfI




###
POST http://localhost:3000/user/tweets/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJuYW1lIjoiQWRhbSBSaWNoYXJkIiwidXNlcm5hbWUiOiJhZGFtIiwicGFzc3dvcmQiOiIkMmIkMTAkWllVQnlhOGhDUjFsZjI0Ly5ud0R3LjlFLm82S2Z0TEg3TnloSU1zZE5lSjJxbW5ENnZQbmEiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjc5NTYzNTI1fQ.vE1LAm6XGlUXldIAHA1CB5SuyvByLdOZZCbOvrujMfI

{
    "tweet": "The Mornings..."
}

###
DELETE  http://localhost:3000/tweets/5/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJuYW1lIjoiQWRhbSBSaWNoYXJkIiwidXNlcm5hbWUiOiJhZGFtIiwicGFzc3dvcmQiOiIkMmIkMTAkWllVQnlhOGhDUjFsZjI0Ly5ud0R3LjlFLm82S2Z0TEg3TnloSU1zZE5lSjJxbW5ENnZQbmEiLCJnZW5kZXIiOiJtYWxlIiwiaWF0IjoxNjc5NTYzNTI1fQ.vE1LAm6XGlUXldIAHA1CB5SuyvByLdOZZCbOvrujMfI





